spring:
  datasource:
    username: sa
    password: password
    url: jdbc:h2:./target/local_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true